export const EmployeeData=[
    {
        id:1,
        firstName:"Prerna",
        lastName:"Nimje",
        age:20
    },
    {
        id:2,
        firstName:"Sakshi",
        lastName:"Nikhate",
        age:21
    },
    {
        id:3,
        firstName:"Rashi",
        lastName:"Tingne",
        age:19
    },
]